
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8000:8000
    networks:
      - app

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always

    volumes:
       - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: menrva
    networks:
      - app

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - app

networks:
  app:
    driver: bridge